import { gColors } from '../../GlobalStyles';

export const eventStyles = {
  1: { backgroundColor: 'orange', color: 'white' },
  10: { backgroundColor: 'orange', color: 'white' },
  11: { backgroundColor: 'orange', color: 'white', fontSize: 12 },
  12: { backgroundColor: 'orange', color: 'white', fontSize: 12 },
  13: { backgroundColor: '#1E88E5', color: 'white' },
  15: { backgroundColor: 'orange', color: 'white', fontSize: 10 },
  16: { backgroundColor: 'orange', color: 'white', fontSize: 10 },
  17: { backgroundColor: 'orange', color: 'white', fontSize: 12 },
  18: { backgroundColor: 'orange', color: 'white', fontSize: 12 },
  30: { backgroundColor: '#EEEEEE', color: 'black' },
  31: { backgroundColor: 'yellowgreen', color: 'white', fontWeight: '600', fontSize: 22 },
  32: { backgroundColor: '#EEEEEE', color: 'black' },
  33: { backgroundColor: '#EEEEEE', color: 'black' },
  34: { backgroundColor: '#EEEEEE', color: 'black' },
  40: { backgroundColor: '#EEEEEE', color: 'black' },
  41: { backgroundColor: '#EEEEEE', color: 'black' },
  42: { backgroundColor: '#EEEEEE', color: 'black' },
  50: { backgroundColor: '#EEEEEE', color: 'black' },
  61: { backgroundColor: gColors.cardsType1, color: 'black' },
  62: { backgroundColor: gColors.cardsType2, color: 'white' },
  63: { backgroundColor: gColors.cardsType3, color: 'white' },
  64: { backgroundColor: gColors.cardsType4, color: 'white' },
  65: { backgroundColor: gColors.cardsType5, color: 'white' },
  70: { backgroundColor: '#EEEEEE', color: 'black' },
  80: { backgroundColor: '#EEEEEE', color: 'black' },
  100: { backgroundColor: '#1E88E5', color: 'white' },
};
